// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package migr

import (
	"database/sql"
)

type Destination struct {
	ID                     int64
	DestinationName        string
	DestinationType        string
	DestinationDescription string
	Config                 []byte
	UpdatedAt              sql.NullTime
}

type Pipeline struct {
	ID            int64
	SourceID      int64
	DestinationID int64
}

type Source struct {
	ID                int64
	SourceName        string
	SourceType        string
	SourceDescription string
	Config            []byte
	UpdatedAt         sql.NullTime
}
